import type { GraphEdge, GraphNode } from "./types";

export const nodes: GraphNode[] = [
  {
    id: "easter-attack",
    x: 1000,
    y: 20,
    kind: "event",
    initials: "EA",
    name: { si: "පාස්කු ඉරිදා ප්‍රහාරය", en: "Easter Sunday Attacks" },
    role: { si: "2019 අප්‍රේල් 21", en: "21 April 2019" },
    si: "2019 අප්‍රේල් 21 පාස්කු ඉරිදා දින කොළඹ, නිගොම්බෝ සහ බටිකලෝව ප්‍රදේශවල පල්ලි හා හෝටල් කිහිපයකට එල්ල වූ මරාගෙන මැරෙන ත්‍රස්ත ප්‍රහාර මගින් සිය ගණනක් මිය ගියහ. ප්‍රහාරයට පෙර ආරක්ෂක කවුන්සිලයට ලැබුණු පූර්ව බුද්ධි අනතුරු ඇඟවීම් නිසි ලෙස සැලකිල්ලට ගෙන නොතිබුණි.",
    en: "On Easter Sunday, 21 April 2019, a series of coordinated suicide bombings struck churches and hotels in Colombo, Negombo and Batticaloa, killing hundreds. Prior intelligence warnings received by the Security Council are alleged to have not been properly acted upon.",
  },
  {
    id: "hemasiri-fernando",
    x: 720,
    y: 160,
    kind: "person",
    initials: "HF",
    name: { si: "හේමසිරි ප්‍රනාන්දු", en: "Hemasiri Fernando" },
    role: { si: "පාස්කු ප්‍රහාරය සිදුවන විට ආරක්ෂක ලේකම්", en: "Defence Secretary at the time of the attack" },
    si: "පාස්කු ප්‍රහාරය සිදුවන විට ආරක්ෂක ලේකම් ලෙස කටයුතු කළේය. ප්‍රහාරයට පෙර ලැබුණු බුද්ධි අනතුරු ඇඟවීම් සම්බන්ධයෙන් ජනාධිපති කොමිසමේ පරීක්ෂණවලට මුහුණ දුන්නේය.",
    en: "Served as Defence Secretary at the time of the Easter attack. Faced questioning before the Presidential Commission of Inquiry over how the prior intelligence warnings were handled.",
  },
  {
    id: "pujith-jayasundara",
    x: 1280,
    y: 160,
    kind: "person",
    initials: "PJ",
    name: { si: "පූජිත් ජයසුන්දර", en: "Pujith Jayasundara" },
    role: { si: "පොලිස්පති (2015 සැප් - 2019)", en: "Inspector General of Police (Sep 2015 – 2019)" },
    si: "පාස්කු ප්‍රහාරය සිදුවන විට පොලිස්පතිවරයා ලෙස කටයුතු කළේය. ප්‍රහාරයට පෙර ලැබුණු බුද්ධි තොරතුරු සම්බන්ධයෙන් සහ ප්‍රහාරය වැළැක්වීමට ගත් පියවර සම්බන්ධයෙන් ජනාධිපති කොමිසම හමුවේ සාක්ෂි දුන්නේය.",
    en: "Served as Inspector General of Police at the time of the attack. Testified before the Presidential Commission of Inquiry regarding the intelligence received beforehand and the steps taken — or not taken — to prevent the attack.",
  },
  {
    id: "fifty-two-day-govt-crisis",
    x: 1000,
    y: 320,
    kind: "event",
    initials: "52",
    name: { si: "දින 52 ආණ්ඩු අර්බුදය", en: "The \"52-day government\" crisis" },
    role: { si: "2018 ඔක්තෝබර් 26 - දෙසැම්බර්", en: "26 Oct – Dec 2018" },
    si: "2018 ඔක්තෝබර් 26 සිට ආරම්භ වූ ආණ්ඩුක්‍රම ව්‍යවස්ථා අර්බුදය (\"දින 52 ආණ්ඩුව\") හේතුවෙන් රාජ්‍ය ආරක්ෂක ආයතන අතර සම්බන්ධීකරණය බිඳ වැටුණු බව සඳහන් වේ. මෙය පාස්කු ප්‍රහාරයට මාසයකට පෙර සිදු වූ සිදුවීමකි.",
    en: "The constitutional crisis that began on 26 October 2018 — commonly called the \"52-day government\" — is cited as a period in which coordination between state security agencies broke down. This took place only months before the Easter attack.",
  },
  {
    id: "jayaki-de-alwi",
    x: 1620,
    y: 60,
    kind: "person",
    initials: "JD",
    name: { si: "ජයකි ද අල්විස්", en: "Jayaki De Alwis" },
    role: { si: "කමිටුවේ සභාපතිනිය (හිටපු මහාධිකරණ විනිසුරුවරියක්)", en: "Committee Chairperson (Retired High Court Judge)" },
    si: "හිටපු මහාධිකරණ විනිසුරුවරියක් වන ජයකි ද අල්විස් මහත්මිය, උදය ගම්මන්පිල මහතා විසින් පත් කරන ලද කමිටුවේ සභාපතිනිය ලෙස කටයුතු කළාය.",
    en: "A retired High Court judge, Jayaki De Alwis chaired the committee appointed to look into the conduct of senior CID officers, including Ravi Seneviratne.",
  },
  {
    id: "presidential-committee-report",
    x: 1620,
    y: 240,
    kind: "committee",
    initials: "CR",
    name: { si: "කමිටු වාර්තාව", en: "The Committee Report" },
    role: { si: "ගම්මන්පිල විසින් පත් කරන ලද කමිටුව", en: "Committee appointed under Gammanpila" },
    si: "කමිටුව ජනාධිපතිට කරුණු දැක්වීමේ අරමුණෙන් ක්‍රියාත්මක වන අතර අධිකරණමය බලයක් නැත. චෝදනා 11කින් 8කට වැරදිකරු කරමින් පොලිස් කොමිසම මගින් සේවයෙන් පහ කරයි. අදාළ කමිටුවේ අනිකුත් නිළධාරීන් (හිටපු පොලිස්පති, දැනට වැඩ තහනම් වී ඇති දේශබන්දු ආදී අය) ගැන කර ඇති නිර්දේශ ගැන ගම්මන්පිල අවධානය යොමු කර නැත.",
    en: "The committee operates purely to advise the President and has no judicial authority. It found Ravi Seneviratne guilty on 8 of 11 charges, and the Police Commission used this to remove him from service. Critics note that Gammanpila did not draw the same attention to the committee's recommendations regarding other named officers, including a former IGP and others currently under interdiction.",
  },
  {
    id: "committee-retaliation-claim",
    x: 1900,
    y: 140,
    kind: "allegation",
    initials: "PV",
    name: { si: "පුද්ගලික පලි ගැනීමක් ද?", en: "A personal vendetta?" },
    role: { si: "චෝදනාව", en: "Allegation" },
    si: "සුරේෂ් සලේට චෝදනා සහිතව බුද්ධි ප්‍රධානී ලෙසට කටයුතු කිරීම ගැන විරෝධතාවයක් ගම්මන්පිලට කිසිදු විරෝධතාවක් නොතිබුණ ද, රවී සෙනවිරත්නට පුද්ගලික පලි ගැනීම වෙනුවෙන් පත් කළ දූෂිත නිළධාරී මඬුල්ලකින් සමන්විත කමිටුවාර්තාව ඊට වඩා වැදගත් ලෙස සැලකීම පිළිබඳ විරෝධතාවයක් මතු වේ.",
    en: "Critics allege that while Gammanpila raised no objection to Suresh Sallay continuing as intelligence chief despite accusations against him, he treated a committee report — assembled, the allegation claims, by officials with a personal grudge against Ravi Seneviratne — as far more significant.",
  },
  {
    id: "committee-no-new-info",
    x: 1340,
    y: 240,
    kind: "counter-argument",
    initials: "NN",
    name: { si: "කමිටුවේ අලුත් කිසිවක් නැත", en: "Nothing new in the report" },
    role: { si: "ප්‍රතිවාදය", en: "Counter-argument" },
    si: "කමිටු වාර්තාවේ රවී සෙනවිරත්නට ඇති චෝදනාව හැර වෙන කිසිදු අලුත් තොරතුරක් ඇතුළත් වී නැති නිසා මෙය රවී සෙනවිරත්නගේ පුද්ගලික පලි ගැනීමක් ලෙස කර ඇති කමිටුවක් බවට පැහැදිලියි.",
    en: "The argument made in Ravi Seneviratne's defence is that the committee report contains nothing beyond the existing allegation against him — which, it is argued, makes clear the committee was set up as a personal act of retaliation rather than a genuine new inquiry.",
  },
  {
    id: "zahran-hashim",
    x: 60,
    y: 280,
    kind: "person",
    initials: "ZH",
    name: { si: "සහරාන් හෂීම්", en: "Zahran Hashim" },
    role: { si: "ප්‍රහාරයේ ප්‍රධාන සැලසුම්කරු", en: "Alleged mastermind of the attack" },
    si: "පාස්කු ඉරිදා ප්‍රහාරයේ ප්‍රධාන සැලසුම්කරු ලෙස හඳුනාගෙන ඇත. මේට පෙර 2018 මාවනැල්ල ප්‍රදේශයේ බුදු පිළිම වලට හානි කිරීමේ සිදුවීම සමඟ ද සම්බන්ධ කරයි. ප්‍රහාරයට පෙර ඔහුගේ කණ්ඩායම සියලු පුද්ගලික ඩිජිටල් දත්ත (දුරකථන සහ laptop) මකා දැමූ බව සඳහන් වේ.",
    en: "Identified as the principal mastermind behind the Easter Sunday attacks. He is also linked to the 2018 vandalism of Buddha statues in the Mawanella area. It is reported that, ahead of the attack, his group wiped all personal digital data from their phones and laptops.",
  },
  {
    id: "ali-ubaidah",
    x: 60,
    y: 460,
    kind: "person",
    initials: "AU",
    name: { si: "අලි උබයිදා", en: "Ali Ubaidah" },
    role: { si: "සහරාන්ගේ සහචරයෙක්", en: "Associate of Zahran Hashim" },
    si: "සහරාන් හෂීම්ගේ සහචර කල්ලියේ සාමාජිකයෙකි. ඔහුගේ පසුබිම සහ චර්යාව පිළිබඳ විමර්ශන සිදු කර ඇත.",
    en: "A named associate within Zahran Hashim's circle. His background and movements were among the subjects of subsequent investigation.",
  },
  {
    id: "ip-bandara",
    x: 320,
    y: 360,
    kind: "person",
    initials: "IB",
    name: { si: "පොලිස් පරීක්ෂක බණ්ඩාර", en: "IP Bandara" },
    role: { si: "\"Sonic Sonic\" - පොලිස් බුද්ධි අංශය", en: "Codenamed \"Sonic Sonic\" — Police Intelligence" },
    si: "පොලිස් බුද්ධි අංශයේ නිලධාරියෙකි. \"Sonic Sonic\" යන ආරක්ෂිත නාමයෙන් හඳුන්වනු ලැබේ.",
    en: "An officer attached to the Police Intelligence division, referred to in this account by the codename \"Sonic Sonic\".",
  },
  {
    id: "sahara-jasmine",
    x: 320,
    y: 540,
    kind: "person",
    initials: "SJ",
    name: { si: "සහරා ජස්මින්", en: "Sahara Jasmin" },
    role: { si: "සහරාන්ගේ බිරිඳ", en: "Zahran Hashim's wife" },
    si: "සයින්දමරුදු සිදුවීමේ දී ඇය මෝටර් සයිකලයකින් පැන යන්නට ඉඩ ඇති බවට මත පළ වෙයි. දෙවරක් ඇගේ DNA කොටස් එම සිදුවීමට අදාළව හමු නොවුණද, තුන්වන වර කරන ලද DNA විභාගයේ දී ඇගේ DNA කොටස් හමු විය.",
    en: "There is a view that she may have escaped the Sainthamaruthu siege on a motorcycle. While her DNA was not found at the scene in two earlier tests, a third DNA test reportedly did find a match.",
  },
  {
    id: "dna-evidence-allegation",
    x: 60,
    y: 640,
    kind: "allegation",
    initials: "DNA",
    name: { si: "DNA සාක්ෂි පිළිබඳ ප්‍රශ්නය", en: "The DNA evidence question" },
    role: { si: "චෝදනාව", en: "Allegation" },
    si: "තුන්වන වර DNA පරීක්ෂණයක් කිරීමට පෙළැඹුණේ ඇයි ද යන්න සහ එම තුන්වන පරීක්ෂණයේදී පමණක් ගැළපීමක් හමු වූයේ මන්දැයි යන්න ප්‍රශ්නගත කරයි.",
    en: "Questions why a third DNA test was deemed necessary in the first place, and why a match only emerged on that third attempt when the first two had found none.",
  },
  {
    id: "abducted-11-youths",
    x: 320,
    y: 720,
    kind: "event",
    initials: "11",
    name: { si: "තරුණයන් 11 දෙනෙකු අතුරුදන්වීම", en: "Disappearance of 11 youths" },
    role: { si: "කොළඹ අවට", en: "Around Colombo" },
    si: "කොළඹ අවට ප්‍රදේශවල තරුණයන් 11 දෙනෙකු පැහැරගෙන ගොස් අතුරුදන් කිරීම සිදු වූ බව වාර්තා වේ.",
    en: "It is reported that 11 youths from areas around Colombo were abducted and remain unaccounted for.",
  },
  {
    id: "vass-gunawardena",
    x: 60,
    y: 820,
    kind: "person",
    initials: "VG",
    name: { si: "වාස් ගුණවර්ධන", en: "Vass Gunawardena" },
    role: { si: "හිටපු නියෝජ්‍ය පොලිස්පති", en: "Former Deputy Inspector General of Police" },
    si: "නඩුවක් මෙහෙයවීමේ දී ව්‍යාජ සාක්ෂි සැකසූවා යැයි චෝදනා එල්ල වී, ඔහු සහ පුතා විසින් සිරකරුවෙකු ඝාතනය කළ බවට ද සැකපල් වෙයි. මේ චෝදනා මත මාස 10ක් රිමාන්ඩ් බන්ධනාගාර ගතව සිටීමට ඔහුට සිදු විය. මහර බන්ධනාගාරයේ රිමාන්ඩ් භාරයේ සිටියදී ඔහුට කෝවිඩ්-19 ආසාදිත වූ අතර, මහර බන්ධනාගාරයේ වාර්තා වූ පළමු කොවිඩ් ආසාදිතයා ඔහු වූ බැවින් මෙය ඔහුව ඝාතනය කිරීමට දරන ලද උත්සාහයක් යැයි සැක කරති. පසුව ශ්‍රී ලංකා මානව හිමිකම් කොමිෂන් සභාවේ මැදිහත්වීම මත ඔහු IDH රෝහලට ඇතුළත් කරනු ලැබීය.",
    en: "Accused of fabricating evidence while leading an investigation, and separately suspected, along with his son, of killing a prisoner. These allegations led to him spending 10 months on remand. While held at Mahara Prison, he contracted COVID-19 — the prison's first reported case — which some suspect was no accident but an attempt on his life. He was later admitted to the IDH hospital following intervention by the Human Rights Commission of Sri Lanka.",
  },
  {
    id: "ravi-seneviratne",
    x: 760,
    y: 540,
    kind: "person",
    initials: "RS",
    name: { si: "රවී සෙනවිරත්න", en: "Ravi Seneviratne" },
    role: { si: "මහජන ආරක්ෂක අමාත්‍යාංශයේ ලේකම් (වර්තමාන)", en: "Secretary, Ministry of Public Security (current)" },
    si: "අපරාධ පරීක්ෂණ දෙපාර්තමේන්තුව (CID) භාර නියෝජ්‍ය පොලිස්පති ලෙස පාස්කු ප්‍රහාරයට සම්බන්ධ විමර්ශන කරමින් සිටියේය. ගෝඨාභය රාජපක්ෂ ජනාධිපතිවරයා ලෙස පත්වීමත් සමඟම, ඔහු සහ ශානි අබේසේකර එම විමර්ශන වලින් ඉවත් කරනු ලැබීය. වෘත්තීය ජීවිතයට විශ්‍රාම යාමෙන් පසුව ඔහු NPP පක්ෂයට සමීපව කටයුතු කළේය. දැනට මහජන ආරක්ෂක අමාත්‍යාංශයේ ලේකම් ලෙස කටයුතු කරයි.",
    en: "As the Deputy Inspector General of Police in charge of the CID, he led investigations connected to the Easter attack. Soon after Gotabaya Rajapaksa became President, both he and Shani Abeysekara were removed from those investigations. After retiring from the police, he became closely associated with the NPP. He currently serves as Secretary of the Ministry of Public Security.",
  },
  {
    id: "shani-abeysekara",
    x: 760,
    y: 720,
    kind: "person",
    initials: "SA",
    name: { si: "ශානි අබේසේකර", en: "Shani Abeysekara" },
    role: { si: "හිටපු CID අධ්‍යක්ෂක (ජ්‍යෙෂ්ඨ පොලිස් අධිකාරී)", en: "Former Director, CID (Senior Superintendent of Police)" },
    si: "අපරාධ පරීක්ෂණ දෙපාර්තමේන්තුවේ (CID) හිටපු අධ්‍යක්ෂකවරයා. ශානි සහ රවී, නීති ගරුක නිළධාරීන් ලෙස ලබා ඇති කීර්තිනාමය නිසා, නීතිය හමුවේ දඬුවම් පැමිණිය හැකි දූෂිත නිළධාරීන් සහ දේශපාලනඥයන් ආරක්ෂා කිරීමට ලෙහෙසිම ක්‍රමය ලෙස ඔහු සහ රවී එම තනතුරුවලින් ඉවත් කිරීම සැලකේ. මාස 10ක් රක්ෂිත බන්ධනාගාරයට යැවූ චෝදනාවෙන් පසුව නිදහස් විය.",
    en: "Former Director of the CID. Because of the reputation he and Ravi Seneviratne built as officers who enforced the law without fear or favour, removing them from their posts is described as the easiest way to shield corrupt officials and politicians from facing justice. He was previously held in remand for 10 months before being cleared of the charges against him.",
  },
  {
    id: "shani-investigation-record",
    x: 480,
    y: 820,
    kind: "counter-argument",
    initials: "REC",
    name: { si: "විමර්ශන කිහිපයක ඉතිහාසය", en: "A record of major investigations" },
    role: { si: "ප්‍රතිවාදය", en: "Counter-argument" },
    si: "ශානි අබේසේකරගේ අධීක්ෂණයෙන් ක්‍රියාත්මක වූ විමර්ශන කිහිපයක් - මාධ්‍යවේදී ලසන්ත වික්‍රමතුංග ඝාතනය, රගර් ක්‍රීඩක වසීම් තාජුදීන් ඝාතනය, භාරත ලක්ෂ්මන් ප්‍රේමචන්ද්‍ර ඝාතනය, රෝයල් පාර්ක් ඝාතනය, මොහොමඩ් සියාම් ඝාතනය, අඟුලාන ද්විත්ව මිනීමැරුම, උඩතලවින්න ඝාතනය, රතුපස්වල වෙඩි තැබීම වැනි විමර්ශන ඇතුළුව.",
    en: "A list of major, politically sensitive cases investigated under Shani Abeysekara's watch is cited in his defence — including the murders of journalist Lasantha Wickrematunge, rugby player Wasim Thajudeen, politician Bharatha Lakshman Premachandra, the Royal Park murder, the killing of Mohomed Siyam, the Akurana double murder, the Udathalawinna killing, and the Rathupaswala shooting investigation.",
  },
  {
    id: "removal-from-investigation",
    x: 760,
    y: 380,
    kind: "allegation",
    initials: "RM",
    name: { si: "විමර්ශනවලින් ඉවත් කිරීම", en: "Removed from the investigation" },
    role: { si: "චෝදනාව", en: "Allegation" },
    si: "ගෝඨාභය රාජපක්ෂ ජනාධිපතිවරයාව පත්වීමත් සමඟම මුලින්ම කළේ රවී සහ අපරාධ පරීක්ෂණ දෙපාර්තමේන්තුවේ අධ්‍යක්ෂ ශානි අබේසේකර වැනි වග කිවයුතු නිළධාරීන් එම විමර්ශනවලින් ඉවත් කිරීමයි.",
    en: "The allegation is that, immediately upon becoming President, Gotabaya Rajapaksa's first act was to remove accountable officers like Ravi Seneviratne and CID Director Shani Abeysekara from the relevant investigations.",
  },
  {
    id: "no-legal-order-defense",
    x: 460,
    y: 580,
    kind: "counter-argument",
    initials: "NL",
    name: { si: "නෛතික නියෝගයක් නොතිබුණි", en: "No lawful order was given" },
    role: { si: "ප්‍රතිවාදය", en: "Counter-argument" },
    si: "රවී සෙනවිරත්නට ඒ සම්බන්ධව නියෝගයක් පොලිස්පති හරහා ලැබී නැති අතර, එවන් නියෝගයක් නැතුව ඔහුට ඒ සම්බන්ධව ක්‍රියා කිරීමට නෛතික බලයක් නැති බව. රවී සෙනවිරත්න විසින් පාස්කු ප්‍රහාරය වළක්වා ගැනීමට අදාළ ලිපිය නොලැබුණද, ඔහුට පැවරී ඇති බලතල වලට අනුව ක්‍රියා කර ඇති අතර, රනිල් වික්‍රමසිංහ සෘජුවම සම්බන්ධ කර ගැනීමට උත්සාහ කර ඇති අතර, දුරකථන් සම්බන්ධ වී නොමැත. මේ සඳහා සාක්ෂි ලෙස දුරකථන වාර්තා යොදා ගත හැක.",
    en: "The defence is that no formal order ever reached Ravi Seneviratne through the IGP, and without one he had no legal authority to act unilaterally. Although he never received the specific letter relevant to preventing the attack, he is said to have acted within the powers he did hold, and to have attempted to reach Ranil Wickremesinghe directly — phone records, it is argued, show no contact ever took place, and could be produced as evidence.",
  },
  {
    id: "palitha-siriwardena",
    x: 1020,
    y: 600,
    kind: "person",
    initials: "PS",
    name: { si: "පාලිත සිරිවර්ධන", en: "Palitha Siriwardena" },
    role: { si: "හිටපු SSP, හිටපු CID නිළධාරියෙක්", en: "Former SSP, former CID officer" },
    si: "ශානි සහ රවී විසින් පොලිස්පති නියමයෙන් පාලිතට එරෙහිව පරීක්ෂණයක් කරන ලදී. ඔහුගේ පැමිණිල්ලක් මත තමයි අපරාධ පරීක්ෂණ දෙපාර්තමේන්තුවට රවී ගැන පරීක්ෂණ ආරම්භ වන්නේ.",
    en: "Was himself investigated by Shani and Ravi, on the IGP's orders. It was his later complaint that triggered the CID's own investigation into Ravi Seneviratne.",
  },
  {
    id: "palitha-complaint-against-ravi",
    x: 1020,
    y: 760,
    kind: "allegation",
    initials: "PC",
    name: { si: "පාලිතගේ පැමිණිල්ල", en: "Palitha's complaint" },
    role: { si: "චෝදනාව", en: "Allegation" },
    si: "ඔහු විසින් පැමිණිල්ල කරද්දී කෙළින්ම ඉල්ලීමක් කරනවා, මේ පරීක්ෂණය සඳහා ඉන්දික සිල්වා නම් පුද්ගලයා යොදා ගන්න කියලා.",
    en: "When filing the complaint, he is said to have made a direct request that a specific individual, Indika Silva, be assigned to handle the resulting investigation.",
  },
  {
    id: "indika-de-silva",
    x: 1280,
    y: 700,
    kind: "person",
    initials: "ID",
    name: { si: "ඉන්දික ද සිල්වා", en: "Indika De Silva" },
    role: { si: "CID අධ්‍යක්ෂක (වර්තමාන)", en: "Director, CID (current)" },
    si: "වර්තමාන CID අධ්‍යක්ෂකවරයා. පාලිත සිරිවර්ධනගේ පැමිණිල්ල මත රවී සෙනවිරත්න සම්බන්ධ පරීක්ෂණය භාර වූයේ ඔහුටය.",
    en: "Currently serves as Director of the CID. He was the officer specifically named, at Palitha Siriwardena's request, to take charge of the investigation into Ravi Seneviratne.",
  },
  {
    id: "talk-show-segment",
    x: 480,
    y: 380,
    kind: "event",
    initials: "TV",
    name: { si: "\"Talk\" එකක් තිබුණාද?", en: "Was there a \"talk\"?" },
    role: { si: "රූපවාහිනී වැඩසටහනක කොටසක්", en: "Television discussion segment" },
    si: "පාස්කු ප්‍රහාරයේ සැකකරුවෙකු සමඟ \"talk\" එකක් තිබුණාද කියා මට අහන්න සිදුවුණා, යනුවෙන් රූපවාහිනී වැඩසටහනක දී චෝදනා මතු කරන ලදී.",
    en: "During a televised discussion, a presenter raised the question of whether there had been a \"talk\" — implying back-channel contact — between officials and a suspect in the Easter attack.",
  },
  {
    id: "npp-retired-police-collective",
    x: 1020,
    y: 440,
    kind: "event",
    initials: "NPP",
    name: { si: "NPP \"Retired Police Collective\"", en: "NPP's Retired Police Collective" },
    role: { si: "පුවත් වාර්තාව", en: "News report" },
    si: "Ravi Seneviratne, Shani Abeysekara join NPP's Retired Police Collective. වෘත්තීය ජීවිතයට විශ්‍රාම යාමෙන් පසුව දෙදෙනාම NPP පක්ෂයට සමීපව කටයුතු කළහ.",
    en: "A news report on Ravi Seneviratne and Shani Abeysekara joining the NPP-aligned Retired Police Collective after retiring from active police service.",
  },
  {
    id: "court-no-fault-found",
    x: 460,
    y: 720,
    kind: "counter-argument",
    initials: "CT",
    name: { si: "අධිකරණය චෝදනා කළේ නැත", en: "No fault found by the courts" },
    role: { si: "ප්‍රතිවාදය", en: "Counter-argument" },
    si: "පාස්කු ප්‍රහාරය හරහා වගකීම් පැහැර හැරීමට එරෙහිව මූලික අයිතිවාසිකම් නඩුවක් පැවරිණි. එයින් රාජ්‍ය සේවකයන්ට සහ දේශපාලනඥයන්ට එරෙහිව තීන්දු බොහෝමයක් ලැබිණි (හිටපු ජනාධිපති මෛත්‍රීපාල, පොලිස්පති, නිලන්ත ජයවර්ධන ඇතුළු). නමුත් රවී හෝ ශානිට එරෙහිව කිසිදු ක්‍රියාමාර්ගයක් නොගැනුණි. රවී සෙනවිරත්නට එම ලියුම ලැබීම ගැන අදාළ නඩුවේ ද අවධානය යොමු වී තිබුණද, ඔහුට විරුද්ධව චෝදනාවක් ලැබිය හැකි කරුණක් මතු නොවූ නිසා ඔහුට විරුද්ධව අධිකරණය ක්‍රියා කර තිබුණේ නැත.",
    en: "A fundamental rights case was filed over the failure to act on Easter attack-related warnings. It resulted in adverse findings against several state officials and politicians — including former President Maithripala Sirisena, the IGP, and Nilantha Jayawardena — but no action was taken against either Ravi or Shani. While the case did examine whether the relevant letter reached Ravi Seneviratne, no basis for a charge against him emerged, and the courts took no action against him.",
  },
  {
    id: "gotabaya-rajapaksa",
    x: 1340,
    y: 540,
    kind: "person",
    initials: "GR",
    name: { si: "ගෝඨාභය රාජපක්ෂ", en: "Gotabaya Rajapaksa" },
    role: { si: "ජනාධිපති (2019 නොවැ 18 - 2022 ජූලි 14)", en: "President (18 Nov 2019 – 14 Jul 2022)" },
    si: "2019 නොවැම්බර් 18 සිට 2022 ජූලි 14 දක්වා ශ්‍රී ලංකාවේ ජනාධිපතිවරයා ලෙස කටයුතු කළේය. ඔහු පත්වීමෙන් දින 5ක් ඇතුළත රවී සෙනවිරත්න සහ ශානි අබේසේකරව පාස්කු ප්‍රහාර විමර්ශනවලින් ඉවත් කළ බව චෝදනා කරයි.",
    en: "Served as President of Sri Lanka from 18 November 2019 to 14 July 2022. It is alleged that within days of taking office, he had Ravi Seneviratne and Shani Abeysekara removed from the Easter attack investigations.",
  },
  {
    id: "maithripala-sirisena",
    x: 1620,
    y: 440,
    kind: "person",
    initials: "MS",
    name: { si: "මෛත්‍රීපාල සිරිසේන", en: "Maithripala Sirisena" },
    role: { si: "හිටපු ජනාධිපති", en: "Former President" },
    si: "පාස්කු ප්‍රහාරය සිදු වූ අවස්ථාවේ ජනාධිපතිවරයා. වගකීම් පැහැර හැරීමට එරෙහි මූලික අයිතිවාසිකම් නඩුවේ ඔහුට එරෙහිව තීන්දු ලැබිණි.",
    en: "President at the time of the Easter attack. The fundamental rights case over the dereliction of duty in failing to act on intelligence warnings returned an adverse finding against him.",
  },
  {
    id: "ranil-wickremesinghe",
    x: 1340,
    y: 700,
    kind: "person",
    initials: "RW",
    name: { si: "රනිල් වික්‍රමසිංහ", en: "Ranil Wickremesinghe" },
    role: { si: "හිටපු අගමැති / ජනාධිපති", en: "Former Prime Minister / President" },
    si: "පාස්කු ප්‍රහාරය සිදු වූ අවස්ථාවේ අග්‍රාමාත්‍යවරයා ලෙස කටයුතු කළේය. රවී සෙනවිරත්න ඔහුව සෘජුවම සම්බන්ධ කර ගැනීමට උත්සාහ කළ බව කියනු ලැබේ, නමුත් දුරකථන් සම්බන්ධ වී නොමැත. පසුව ජනාධිපතිවරයා ලෙස, රවී සහ ශානිට එරෙහිව චෝදනා විමර්ශනය කිරීම සඳහා කමිටුවක් පත් කළේය.",
    en: "Was Prime Minister at the time of the Easter attack. Ravi Seneviratne reportedly attempted to reach him directly, though phone records show no contact was made. Later, as President, he appointed the committee that examined the allegations against Ravi and Shani.",
  },
  {
    id: "udaya-gammanpila",
    x: 1620,
    y: 760,
    kind: "person",
    initials: "UG",
    name: { si: "උදය ගම්මන්පිල", en: "Udaya Gammanpila" },
    role: { si: "හිටපු පාර්ලිමේන්තු මන්ත්‍රී (2017-2024)", en: "Former Member of Parliament (2017–2024)" },
    si: "කමිටු වාර්තාව මතු කරමින් රවී සෙනවිරත්නට එරෙහිව චෝදනා ඉස්මතු කරයි. සුරේෂ් සලේට චෝදනා සහිතව බුද්ධි ප්‍රධානී ලෙස කටයුතු කිරීම ගැන කිසිදු විරෝධතාවක් නොතිබුණද, රවී සෙනවිරත්නට එරෙහි කමිටුවාර්තාව ඊට වඩා වැදගත් ලෙස සැලකූ බව චෝදනා කරයි. අදාළ කමිටුවේ අනිකුත් නිළධාරීන් ගැන කර ඇති නිර්දේශ ගැන ඔහු අවධානය යොමු කර නැති බවද සඳහන් වේ.",
    en: "Has publicly pressed the allegations against Ravi Seneviratne using the committee report. Critics note that he raised no objection to Suresh Sallay continuing as intelligence chief despite accusations against him, while treating the committee findings against Seneviratne as far more significant — and that he has not drawn similar attention to the same report's recommendations regarding other named officers.",
  },
  {
    id: "nilantha-jayawardena",
    x: 1900,
    y: 540,
    kind: "person",
    initials: "NJ",
    name: { si: "නිලන්ත ජයවර්ධන", en: "Nilantha Jayawardena" },
    role: { si: "බුද්ධි ප්‍රධානී", en: "Director, State Intelligence Service" },
    si: "පාස්කු ප්‍රහාරය සිදුවන විට රාජ්‍ය බුද්ධි අංශයේ ප්‍රධානියා. ප්‍රහාරයට පෙර ලැබුණු බුද්ධි අනතුරු ඇඟවීම් සිදුවීම් වලට අදාළව මූලික අයිතිවාසිකම් නඩුවේ ඔහුට එරෙහිව තීන්දු ලැබිණි.",
    en: "Headed the State Intelligence Service at the time of the Easter attack. The fundamental rights case over the failure to act on prior warnings returned an adverse finding against him as well.",
  },
  {
    id: "suresh-sallay",
    x: 2160,
    y: 540,
    kind: "person",
    initials: "SS",
    name: { si: "සුරේෂ් සලේ", en: "Suresh Sallay" },
    role: { si: "බුද්ධි ප්‍රධානී (හිටපු හමුදා බුද්ධි නිළධාරියා)", en: "Intelligence chief (former military intelligence officer)" },
    si: "සුරේෂ් සලේට චෝදනා සහිතව බුද්ධි ප්‍රධානී ලෙස කටයුතු කිරීම ගැන විරෝධතාවයක් මතුවී ඇත. සලේට මුස්ලිම් සංවිධාන සමඟ සම්බන්ධතා තිබූ බව සහ ඔහුට ඇති ප්‍රබල චෝදනාවක් වශයෙන් සහය දැක්වූ බවට සාක්ෂි ඇති බව සඳහන් වේ.",
    en: "His continued role as intelligence chief, despite outstanding accusations against him, has drawn objection. He is said to have had links with Muslim organisations, and there are claims of evidence pointing to him lending support relevant to a serious allegation against him.",
  },
  {
    id: "channel4-mastermind-claim",
    x: 1900,
    y: 700,
    kind: "allegation",
    initials: "C4",
    name: { si: "Channel 4 \"මහ මොළකරු\" චෝදනාව", en: "Channel 4's \"mastermind\" claim" },
    role: { si: "චෝදනාව", en: "Allegation" },
    si: "මහ මොළකරු බවට Channel 4 චැනලය චෝදනා කරයි. රනිල් සහ රාජපක්ෂලාට එරෙහිව මාධ්‍ය නිවේදන තියමින් පෙනී සිටියි.",
    en: "Channel 4 has alleged a far more central, orchestrating role for figures it names as masterminds, while publicly issuing statements directed against both Ranil Wickremesinghe and the Rajapaksas.",
  },
  {
    id: "presidential-commission",
    x: 900,
    y: 940,
    kind: "legal",
    initials: "PC",
    name: { si: "ජනාධිපති කොමිසම", en: "Presidential Commission of Inquiry" },
    role: { si: "පාස්කු ප්‍රහාරය පිළිබඳ විමර්ශන කොමිසම", en: "Inquiry into the Easter Attack" },
    si: "පාස්කු ප්‍රහාරය පිළිබඳ සොයා බැලීම සඳහා පත් කරන ලද ජනාධිපති කොමිසම, ආරක්ෂක කවුන්සිලයට ලැබුණු පූර්ව අනතුරු ඇඟවීම් ගැන සඳහන් කරයි. රනිල් විසින් කොමිසමට අදාළ දත්ත ලබා දෙන ලෙස කී බව සඳහන් වේ.",
    en: "The Presidential Commission of Inquiry set up to investigate the Easter attack examined the prior warnings received by the Security Council. Ranil Wickremesinghe is noted as having instructed that relevant data be handed over to the Commission.",
  },
  {
    id: "fr-case-against-ravi-shani",
    x: 640,
    y: 940,
    kind: "allegation",
    initials: "FR",
    name: { si: "මූලික අයිතිවාසිකම් නඩුව", en: "The fundamental rights case" },
    role: { si: "චෝදනාව", en: "Allegation" },
    si: "පාස්කු ප්‍රහාරය හරහා වගකීම් පැහැර හැරීමට එරෙහිව මූලික අයිතිවාසිකම් නඩුවක් පැවරිණි. රාජ්‍ය සේවකයන්ට සහ දේශපාලනඥයන්ට එරෙහිව තීන්දු බොහෝමයක් ලැබිණි.",
    en: "A fundamental rights case was brought over the dereliction of duty surrounding the Easter attack, resulting in adverse rulings against a number of state officials and politicians.",
  },
  {
    id: "pillayan-pta-case",
    x: 1160,
    y: 940,
    kind: "legal",
    initials: "PTA",
    name: { si: "පිල්ලයාන් - PTA නඩුව", en: "Pillayan's PTA case" },
    role: { si: "2025 අප්‍රේල්", en: "April 2025" },
    si: "පිල්ලයාන් (සිවනේසතුරේ චන්ද්‍රකාන්තන්) වෙනුවෙන් ත්‍රස්තවාද වැළැක්වීමේ පනත (PTA) යටතේ අත් අඩංගුවේ සිටියදී පෙනී සිටි නීතීඥයෙකි.",
    en: "Refers to legal representation for Pillayan (Sivanesathurai Chandrakanthan) while he was held in detention under the Prevention of Terrorism Act (PTA) in April 2025.",
  },
];

export const edges: GraphEdge[] = [
  { id: "e1", source: "easter-attack", target: "hemasiri-fernando" },
  { id: "e2", source: "easter-attack", target: "pujith-jayasundara" },
  { id: "e3", source: "easter-attack", target: "zahran-hashim" },
  { id: "e4", source: "easter-attack", target: "fifty-two-day-govt-crisis" },
  { id: "e5", source: "hemasiri-fernando", target: "presidential-commission" },
  { id: "e6", source: "pujith-jayasundara", target: "presidential-commission" },
  { id: "e7", source: "zahran-hashim", target: "ali-ubaidah" },
  { id: "e8", source: "zahran-hashim", target: "sahara-jasmine" },
  { id: "e9", source: "zahran-hashim", target: "ip-bandara" },
  { id: "e10", source: "sahara-jasmine", target: "dna-evidence-allegation" },
  { id: "e11", source: "ip-bandara", target: "abducted-11-youths" },
  { id: "e12", source: "ip-bandara", target: "vass-gunawardena" },
  { id: "e13", source: "vass-gunawardena", target: "shani-abeysekara" },
  { id: "e14", source: "ravi-seneviratne", target: "shani-abeysekara" },
  { id: "e15", source: "ravi-seneviratne", target: "removal-from-investigation" },
  { id: "e16", source: "shani-abeysekara", target: "removal-from-investigation" },
  { id: "e17", source: "removal-from-investigation", target: "gotabaya-rajapaksa" },
  { id: "e18", source: "removal-from-investigation", target: "no-legal-order-defense" },
  { id: "e19", source: "shani-abeysekara", target: "shani-investigation-record" },
  { id: "e20", source: "ravi-seneviratne", target: "palitha-siriwardena" },
  { id: "e21", source: "palitha-siriwardena", target: "palitha-complaint-against-ravi" },
  { id: "e22", source: "palitha-complaint-against-ravi", target: "indika-de-silva" },
  { id: "e23", source: "indika-de-silva", target: "ravi-seneviratne" },
  { id: "e24", source: "ravi-seneviratne", target: "fr-case-against-ravi-shani" },
  { id: "e25", source: "fr-case-against-ravi-shani", target: "court-no-fault-found" },
  { id: "e26", source: "court-no-fault-found", target: "no-legal-order-defense" },
  { id: "e27", source: "ravi-seneviratne", target: "talk-show-segment" },
  { id: "e28", source: "shani-abeysekara", target: "talk-show-segment" },
  { id: "e29", source: "talk-show-segment", target: "channel4-mastermind-claim" },
  { id: "e30", source: "ravi-seneviratne", target: "npp-retired-police-collective" },
  { id: "e31", source: "shani-abeysekara", target: "npp-retired-police-collective" },
  { id: "e32", source: "gotabaya-rajapaksa", target: "maithripala-sirisena" },
  { id: "e33", source: "gotabaya-rajapaksa", target: "ranil-wickremesinghe" },
  { id: "e34", source: "ranil-wickremesinghe", target: "presidential-committee-report" },
  { id: "e35", source: "udaya-gammanpila", target: "presidential-committee-report" },
  { id: "e36", source: "presidential-committee-report", target: "jayaki-de-alwi" },
  { id: "e37", source: "presidential-committee-report", target: "committee-retaliation-claim" },
  { id: "e38", source: "committee-retaliation-claim", target: "ravi-seneviratne" },
  { id: "e39", source: "presidential-committee-report", target: "committee-no-new-info" },
  { id: "e40", source: "udaya-gammanpila", target: "suresh-sallay" },
  { id: "e41", source: "udaya-gammanpila", target: "channel4-mastermind-claim" },
  { id: "e42", source: "suresh-sallay", target: "channel4-mastermind-claim" },
  { id: "e43", source: "nilantha-jayawardena", target: "suresh-sallay" },
  { id: "e44", source: "nilantha-jayawardena", target: "easter-attack" },
  { id: "e45", source: "ranil-wickremesinghe", target: "ravi-seneviratne" },
  { id: "e46", source: "fr-case-against-ravi-shani", target: "maithripala-sirisena" },
  { id: "e47", source: "fr-case-against-ravi-shani", target: "nilantha-jayawardena" },
  { id: "e48", source: "pillayan-pta-case", target: "presidential-commission" },
];
